In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

In [2]:
dataset=tf.data.Dataset.range(10)
for val in dataset:
    print(val.numpy())

0
1
2
3
4
5
6
7
8
9


In [3]:
dataset=tf.data.Dataset.range(10)
dataset=dataset.window(5,shift=1)

for window_dataset in dataset:
    for val in window_dataset:
        print(val.numpy(),end='')
    print()

01234
12345
23456
34567
45678
56789
6789
789
89
9


In [4]:
dataset=tf.data.Dataset.range(10)
dataset=dataset.window(5,shift=1,drop_remainder=True)

for window_dataset in dataset:
    for val in window_dataset:
        print(val.numpy(),end='')
    print()

01234
12345
23456
34567
45678
56789


In [5]:
dataset=tf.data.Dataset.range(10)
dataset=dataset.window(5,shift=1,drop_remainder=True)
dataset=dataset.flat_map(lambda window:window.batch(5))
for window in dataset:
    print(window.numpy())

[0 1 2 3 4]
[1 2 3 4 5]
[2 3 4 5 6]
[3 4 5 6 7]
[4 5 6 7 8]
[5 6 7 8 9]


In [6]:
dataset=tf.data.Dataset.range(10)
dataset=dataset.window(5,shift=1,drop_remainder=True)
dataset=dataset.flat_map(lambda window:window.batch(5))
dataset=dataset.map(lambda window:(window[:-1],window[-1:]))

for x,y in dataset:
    print(x.numpy(),y.numpy())

[0 1 2 3] [4]
[1 2 3 4] [5]
[2 3 4 5] [6]
[3 4 5 6] [7]
[4 5 6 7] [8]
[5 6 7 8] [9]


In [7]:
dataset=tf.data.Dataset.range(10)
dataset=dataset.window(5,shift=1,drop_remainder=True)
dataset=dataset.flat_map(lambda window:window.batch(5))
dataset=dataset.map(lambda window:[window[:-1],window[-1:]])
dataset=dataset.shuffle(buffer_size=10)

for x,y in dataset:
    print(x.numpy(),y.numpy())

[3 4 5 6] [7]
[0 1 2 3] [4]
[2 3 4 5] [6]
[5 6 7 8] [9]
[1 2 3 4] [5]
[4 5 6 7] [8]


In [8]:
dataset=tf.data.Dataset.range(10).window(5,shift=1,drop_remainder=True)\
        .flat_map(lambda window:window.batch(5))\
        .map(lambda window:[window[:-1],window[-1:]])\
        .shuffle(buffer_size=10)\
        .batch(2).prefetch(1)

for x,y in dataset:
    print("x = \n{} \n y = \n{} ".format(x.numpy(),y.numpy()))

Cause: could not parse the source code:

        .flat_map(lambda window:window.batch(5))\
        .map(lambda window:[window[:-1],window[-1:]])\
        .shuffle(buffer_size=10)\
        .batch(2).prefetch(1)

This error may be avoided by creating the lambda in a standalone statement.

Cause: could not parse the source code:

        .flat_map(lambda window:window.batch(5))\
        .map(lambda window:[window[:-1],window[-1:]])\
        .shuffle(buffer_size=10)\
        .batch(2).prefetch(1)

This error may be avoided by creating the lambda in a standalone statement.

Cause: could not parse the source code:

        .map(lambda window:[window[:-1],window[-1:]])\
        .shuffle(buffer_size=10)\
        .batch(2).prefetch(1)

This error may be avoided by creating the lambda in a standalone statement.

Cause: could not parse the source code:

        .map(lambda window:[window[:-1],window[-1:]])\
        .shuffle(buffer_size=10)\
        .batch(2).prefetch(1)

This error may be avoided